### ISSUE TITLE
server run 不起來 ( address already in use :::4000)

### ISSUE THREAD

**Issue by huang3t** [ntuee-webprogramming/hack2-QAs#12]
events.js:377
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::4000
    at Server.setupListenHandle [as _listen2] (net.js:1331:16)
    at listenInCluster (net.js:1379:12)
    at Server.listen (net.js:1465:7)
    at Function.listen (/mnt/c/Users/User/Desktop/wp1101/hack2/node_modules/express/lib/application.js:618:24)
    at Object.<anonymous> (/mnt/c/Users/User/Desktop/wp1101/hack2/server/server.js:40:5)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Module._compile (/mnt/c/Users/User/Desktop/wp1101/hack2/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Object.newLoader [as .js] (/mnt/c/Users/User/Desktop/wp1101/hack2/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:950:32)
Emitted 'error' event on Server instance at:
    at emitErrorNT (net.js:1358:8)
    at processTicksAndRejections (internal/process/task_queues.js:82:21) {
  code: 'EADDRINUSE',
  errno: -98,
  syscall: 'listen',
  address: '::',
  port: 4000
}
[nodemon] app crashed - waiting for file changes before starting...

**Comment by raywu0123** [comment]
這是因為 nodemon 前一次沒有正確關閉導致同個 port 被佔用。
請問你的作業系統是?

**Comment by huang3t** [comment]
我用windows, 有用wsl (ubuntu 1804)
我現在用port 5000就可以
請問一定要用4000嗎

**Comment by ntuee-webprogramming** [comment]
檢查一下你有沒有其他的 app 正在跑，佔用了 4000 port

**Comment by raywu0123** [comment]
可以用這些指令檢查哪個 process 在佔用 port 4000
https://unix.stackexchange.com/questions/106561/finding-the-pid-of-the-process-using-a-specific-port
