### ISSUE TITLE
UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON

### ISSUE THREAD

**Issue by Rookieason** [ntuee-webprogramming/hack2-QAs#39]

**Comment by raywu0123** [comment]
可以麻煩你附上詳細的 error message 嗎
不然也不知道是哪一行噴這個 error

**Comment by Rookieason** [comment]
(node:2192) UnhandledPromiseRejectionWarning: TypeError: Converting circular structure to JSON
    --> starting at object with constructor 'Topology'
    |     property 's' -> object with constructor 'Object'
    |     property 'sessionPool' -> object with constructor 'ServerSessionPool'
    --- property 'topology' closes the circle
    at JSON.stringify (<anonymous>)
    at stringify (C:\Users\user\wp1101\hack2\node_modules\express\lib\response.js:1123:12)
    at ServerResponse.json (C:\Users\user\wp1101\hack2\node_modules\express\lib\response.js:260:14)
    at ServerResponse.send (C:\Users\user\wp1101\hack2\node_modules\express\lib\response.js:158:21)
    at _callee$ (C:\Users\user\wp1101\hack2\server\routes\/post.js:38:24)
    at tryCatch (C:\Users\user\wp1101\hack2\node_modules\regenerator-runtime\runtime.js:63:40)
    at Generator.invoke [as _invoke] (C:\Users\user\wp1101\hack2\node_modules\regenerator-runtime\runtime.js:293:22)
    at Generator.next (C:\Users\user\wp1101\hack2\node_modules\regenerator-runtime\runtime.js:118:21)
    at asyncGeneratorStep (C:\Users\user\wp1101\hack2\server\routes\post.js:16:103)
    at _next (C:\Users\user\wp1101\hack2\server\routes\post.js:18:194)
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
